"""Tablas de apoyo para clasificar y parsear instrucciones F32IS."""

from __future__ import annotations


INSTRUCTION_CLASSES = {
    # R / PR simples
    "add": "clase1",
    "sub": "clase1",
    "mul": "clase1",
    "div": "clase1",
    "mod": "clase1",
    "and": "clase1",
    "orr": "clase1",
    "xor": "clase1",
    "sll": "clase1",
    "srl": "clase1",
    "seq": "clase1",
    "seqz": "clase1",
    "padd": "clase1",
    "psub": "clase1",
    "pmul": "clase1",
    "pdiv": "clase1",
    "pmod": "clase1",
    "pand": "clase1",
    "porr": "clase1",
    "pxor": "clase1",
    "pseq": "clase1",
    # I / PI
    "addi": "clase2",
    "subi": "clase2",
    "muli": "clase2",
    "divi": "clase2",
    "modi": "clase2",
    "andi": "clase2",
    "orri": "clase2",
    "xori": "clase2",
    "slli": "clase2",
    "srli": "clase2",
    "seqi": "clase2",
    "paddi": "clase2",
    "psubi": "clase2",
    "pmuli": "clase2",
    "pdivi": "clase2",
    "pmodi": "clase2",
    "pandi": "clase2",
    "porri": "clase2",
    "pxori": "clase2",
    "pseqi": "clase2",
    # M / V
    "ldw": "clase3",
    "ldh": "clase3",
    "ldb": "clase3",
    "stw": "clase3",
    "sth": "clase3",
    "stb": "clase3",
    "ldvw": "clase3",
    "ldvh": "clase3",
    "ldvb": "clase3",
    "stvw": "clase3",
    "stvh": "clase3",
    "stvb": "clase3",
    # ret / nop
    "ret": "clase4",
    "nop": "clase4",
    # B
    "beq": "claseB",
    "bne": "claseB",
    "bgt": "claseB",
    "blt": "claseB",
    "bge": "claseB",
    "ble": "claseB",
    "beqz": "claseB",
    # J / F
    "jal": "claseJ",
    "call": "claseJ",
    "jmp": "claseJ",
    # S
    "login": "claseS",
    "quit": "claseS",
    # T
    "send": "claseT",
    "recv": "claseT",
    # PR compuestas
    "paddadd": "claseE",
    "pxorxor": "claseE",
    "pslladd": "claseE",
    "psrladd": "claseE",
    # Movimientos / cargas
    "mov": "claseMov",
    "pmov": "claseMov",
    "movi": "claseMov",
    "pmovi": "claseMov",
    "li": "claseL",
    "la": "claseL",
    "pli": "claseL",
    "pla": "claseL",
}


NORMAL_REGISTERS = {
    "zero",
    "ra",
    "sp",
    "pc",
    "lr",
    "p0",
    "p1",
    "p2",
    "p3",
    "p4",
    "p5",
    "p6",
    "p7",
    "p8",
    "r0",
    "r1",
    "r2",
    "r3",
    "r4",
    "r5",
    "r6",
    "r7",
    "r8",
    "r9",
    "r10",
    "r11",
    "r12",
    "r13",
    "r14",
    "r15",
    "delta",
    "max",
}


SECURE_REGISTERS = {"ax", "bx", "cx", "dx", "ex", "fx", "gx", "hx"}


SECURE_PRIMARY = {
    "padd": "add",
    "psub": "sub",
    "pmul": "mul",
    "pdiv": "div",
    "pmod": "mod",
    "pand": "and",
    "porr": "orr",
    "pxor": "xor",
    "pseq": "seq",
    "pmov": "mov",
    "paddi": "add",
    "psubi": "sub",
    "pmuli": "mul",
    "pdivi": "div",
    "pmodi": "mod",
    "pandi": "and",
    "porri": "orr",
    "pxori": "xor",
    "pseqi": "seq",
    "pmovi": "mov",
    "paddadd": "add",
    "pxorxor": "xor",
    "pslladd": "sll",
    "psrladd": "srl",
}


SECURE_SECONDARY = {
    "paddadd": "add",
    "pxorxor": "xor",
    "pslladd": "add",
    "psrladd": "add",
}
